export default {
  state: {
    transportToday: [
      {
        ticketNumber: 1,
        onTer: true,
        incomingTime: '08 : 30',
        incomingDate: '10.10.19',
        outgoingTime: '',
        outgoingDate: '',
        carNumber: 'Е 156 ВВ 798',
        carMark: 'Ман',
        trailerNumber: '',
        driverName: 'Фет А.А.',
        driverDocs: '1232543654',
        divisionCode: 234543,
        organisation: 'мажор',
        phone: 2345234234,
        documents: [1234567, 9879878],
        note: '',
        operation: false,
      },
      {
        ticketNumber: 2,
        onTer: false,
        incomingTime: '10 : 50',
        incomingDate: '10.10.19',
        outgoingTime: '14:45',
        outgoingDate: '10.10.19',
        carNumber: 'В 345 АА 788',
        carMark: 'Вольво',
        trailerNumber: '',
        driverName: 'Писец Н.А.',
        driverDocs: '21 23 456234',
        divisionCode: '214-342',
        organisation: 'пек',
        phone: 3645645634,
        documents: [],
        note: '',
        operation: true,
      },
      {
        ticketNumber: 3,
        onTer: true,
        incomingTime: '12 : 20',
        incomingDate: '10.10.19',
        outgoingTime: '',
        outgoingDate: '',
        carNumber: 'Е 001 КХ 737',
        carMark: 'Форд',
        trailerNumber: '',
        driverName: 'Абдалбилбеков А.А.',
        driverDocs: '21 23 456234',
        divisionCode: '341-311',
        organisation: 'DHL',
        phone: 9050055555,
        documents: [],
        note: '',
        operation: true,
      },
      {
        ticketNumber: 4,
        onTer: true,
        incomingTime: '15 : 32',
        incomingDate: '10.10.19',
        outgoingTime: '',
        outgoingDate: '',
        carNumber: 'А 111 АА 758 ',
        carMark: 'Лада Ларгус',
        trailerNumber: '',
        driverName: 'Прокурорских П.П.',
        driverDocs: '43 12 436666',
        divisionCode: '326-221',
        organisation: 'эксТракЭкспедишенТрейд',
        phone: 9881111111,
        documents: [],
        note: '',
        operation: false,
      },
      {
        ticketNumber: 5,
        onTer: true,
        incomingTime: '15 : 32',
        incomingDate: '10.10.19',
        outgoingTime: '',
        outgoingDate: '',
        carNumber: 'А 111 АА 758 ',
        carMark: 'Лада Ларгус',
        trailerNumber: '',
        driverName: 'Прокурорских П.П.',
        driverDocs: '43 12 436666',
        divisionCode: '326-221',
        organisation: 'эксТракЭкспедишенТрейд',
        phone: 9881111111,
        documents: [],
        note: '',
        operation: false,
      },
      {
        ticketNumber: 6,
        onTer: true,
        incomingTime: '15 : 32',
        incomingDate: '10.10.19',
        outgoingTime: '',
        outgoingDate: '',
        carNumber: 'А 111 АА 758 ',
        carMark: 'Лада Ларгус',
        trailerNumber: '',
        driverName: 'Прокурорских П.П.',
        driverDocs: '43 12 436666',
        divisionCode: '326-221',
        organisation: 'эксТракЭкспедишенТрейд',
        phone: 9881111111,
        documents: [],
        note: '',
        operation: false,
      },
      {
        ticketNumber: 7,
        onTer: true,
        incomingTime: '15 : 32',
        incomingDate: '10.10.19',
        outgoingTime: '',
        outgoingDate: '',
        carNumber: 'А 111 АА 758 ',
        carMark: 'Лада Ларгус',
        trailerNumber: '',
        driverName: 'Прокурорских П.П.',
        driverDocs: '43 12 436666',
        divisionCode: '326-221',
        organisation: 'эксТракЭкспедишенТрейд',
        phone: 9881111111,
        documents: [],
        note: '',
        operation: false,
      },
      {
        ticketNumber: 8,
        onTer: true,
        incomingTime: '15 : 32',
        incomingDate: '10.10.19',
        outgoingTime: '',
        outgoingDate: '',
        carNumber: 'А 111 АА 758 ',
        carMark: 'Лада Ларгус',
        trailerNumber: '',
        driverName: 'Прокурорских П.П.',
        driverDocs: '43 12 436666',
        divisionCode: '326-221',
        organisation: 'эксТракЭкспедишенТрейд',
        phone: 9881111111,
        documents: [],
        note: '',
        operation: false,
      },
      {
        ticketNumber: 9,
        onTer: true,
        incomingTime: '15 : 32',
        incomingDate: '10.10.19',
        outgoingTime: '',
        outgoingDate: '',
        carNumber: 'А 111 АА 758 ',
        carMark: 'Лада Ларгус',
        trailerNumber: '',
        driverName: 'Прокурорских П.П.',
        driverDocs: '43 12 436666',
        divisionCode: '326-221',
        organisation: 'эксТракЭкспедишенТрейд',
        phone: 9881111111,
        documents: [],
        note: '',
        operation: false,
      },
      {
        ticketNumber: 10,
        onTer: true,
        incomingTime: '15 : 32',
        incomingDate: '10.10.19',
        outgoingTime: '',
        outgoingDate: '',
        carNumber: 'А 111 АА 758 ',
        carMark: 'Лада Ларгус',
        trailerNumber: '',
        driverName: 'Прокурорских П.П.',
        driverDocs: '43 12 436666',
        divisionCode: '326-221',
        organisation: 'эксТракЭкспедишенТрейд',
        phone: 9881111111,
        documents: [],
        note: '',
        operation: false,
      },
    ],
    transportComps: {
      value: [
        ['dl', 'дл', 'дел', 'деловые', 'линии', 'деловые линии'],
        ['м', 'мажор', 'маж', 'мейджер', 'мейжер', 'мейжор', 'мейджор', 'мейжор', 'major'],
        ['дчл', 'дичел', 'дхл', 'диейчел', 'диейчэл', 'dhl', 'd', 'д'],
        ['пэк', 'пек', 'п', 'пе', 'пэ'],
        [
          'ж',
          'жд',
          'желдор',
          'жилдор',
          'жел',
          'желдорекспедиция',
          'желдорэкспедиция',
          'желдорекспидиция',
          'желдорэкспидиция',
        ],
        ['эйртранс', 'ейртранс', 'ейр', 'эйр', 'айр', 'Эайртранс', 'э', 'а'],
      ],
      colors: ['#8f8f8f', '#f78317', '#df3030', '#5630df', '#4db64d', '#3ecfb7', '#3e3e3e00'],
      label: ['Деловые Линии', 'Major', 'DHL', 'ПЭК', 'Желдор', 'Эйртранс'],
    },
  },
  actions: {
    CREATE_TICKET: ({ state }, payload) => {
      state.transportToday.push(payload)
    },
    PATCH_DOCS: ({ state }, payload) => {
      state.transportToday
        .find((ticket) => ticket.ticketNumber === payload.ticketNumber)
        .documents.push([payload.docs])
    },
  },
  mutations: {},
  getters: {
    allTransportToday: function(state) {
      return state.transportToday
    },
    nextTicketNumber: function(state) {
      return state.transportToday.length + 1
    },
    transComps: function(state) {
      return state.transportComps
    },
  },
}
